### PR TITLE
Add Rust client

### PR DESCRIPTION
**Pull request by NivenT**
Added a Rust client. The code could still use some cleaning up, but it should be good enough for now. Tested on a random CartPole agent.

### CODE REVIEW

**Comment by catherio** [comment]
Thanks for the contribution! This looks great, although I'm new to Rust. What does a user need to include the 'gym' crate and run the tests? Could you include a few lines of comment explaining how to set up and get started?

```shell
~/openai/gym-http-api/binding-rust/tests$ rustc random_agent.rs
random_agent.rs:1:1: 1:18 error: can't find crate for gym [E0463]
random_agent.rs:1 extern crate gym;
                  ^~~~~~~~~~~~~~~~~'
error: aborting due to previous error
```

**Comment by NivenT** [comment]
No problem.
You run the tests using cargo, Rust's package manager. Just run ```cargo test``` from the binding-rust/ directory.
```
~/gym-http-api/binding-rust$ cargo test
     Running target/debug/gym-c3d7cfd3bbc64520

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

     Running target/debug/lib-e45b21c0fb05a553

running 1 test
test test_space_sample ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

     Running target/debug/random_agent-7f48abaedf004426

running 1 test
test main ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests gym

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

For someone using the gym crate from outside of the tests folder (i.e. in their own project), they would need to add it as a dependency in their Cargo.toml file, using a path to a local copy of this repo.
```
# Cargo.toml
[package]
name = "project"
version = "0.0.1"
authors = ["John Doe"]
 
[dependencies.gym]
path = "path/to/binding-rust"
```
It would be possible to make it to where a user would not need to have a local copy of this repo to use the crate. Instead they could format their Cargo.toml file like this
```
# Cargo.toml
[package]
name = "project"
version = "0.0.1"
authors = ["John Doe"]
 
[dependencies]
gym = "*"
```
However, that would require publishing the crate to crates.io. I have never done that before, so I'm not sure what the process is like.

Let me know if I need to clarify anything.

**Comment by leonardoaraujosantos** [comment]
Guys do you know what to do to make those travis tests to pass? (I'm new on travis)

It's possible to use it also to check matlab code?

**Comment by catherio** [comment]
The Travis tests are in disrepair, my apologies :(. Thanks for your contribution!

**Comment by benwr** [comment]
Yay!

**Pull request merged**
