### PR TITLE
Binding clojure

### PR DESCRIPTION
**Pull request by NonaryR**
added clojure client

### CODE REVIEW

**Comment by NonaryR** [comment]
@catherio Hello! Can you please check this PR?

**Comment by catherio** [comment]
I'm no clojure expert, so I'm trusting you on this that it's solid :)

**Comment by NonaryR** [comment]
Yes, it's true =)
But you closed PR and not merged commits, why?

**Comment by catherio** [comment]
Whoops! Just butterfingers. Thanks!

**Pull request merged**
