### PR TITLE
FIX: Multi-dimension observation support for Golang binding

### PR DESCRIPTION
**Pull request by wenkesj**
This pull request adds support for observations with 1-3D slices `binding-go`, i.e. `Pong-v0`, test case failed previously, but now is supported.

CC @unixpickle I made this as readable as I could, let me know what you think.

### CODE REVIEW

**Comment by unixpickle** [comment]
This looks alright, although a lot of scary nesting. Perhaps this could be implemented with recursion, allowing for infinite nesting?

Eventually I (or someone else) should create more rigorous test cases. The demo was kind of my only (informal) test. Testing might have to shell out to Python, but could be better than nothing.

**Comment by unixpickle** [comment]
To elaborate on recursion: after we see that it's a []interface{}, we call normalizeSpaceElem() on the elements, then use reflection to create a slice of those objects. That way, we'd end up with []float64 or [][]float64 or [][][]float64, etc. This could remove a *lot* of redundancy, but we'd have to decide if it's worth using reflection for.

**Comment by wenkesj** [comment]
I agree. This looks better, this should be moved to an actual issue. I just avoided using reflect for the time being but that looks more reasonable.

**Comment by unixpickle** [comment]
@wenkesj should probably close this now in favor of #48.

**Pull request closed without merging**
