### PR TITLE
Major updates for Lua binding 

### PR DESCRIPTION
**Pull request by korymath**
video_callable is a critical function of the monitor, this code allows it to be called by the clients
also fixed a small nit in the readme

### CODE REVIEW

**Comment by korymath** [comment]
Added another change to allow for continuous (Box) action spaces.

[1aafe4b](https://github.com/openai/gym-http-api/pull/11/commits/1aafe4b334b9207334f1d61a9fc89a290cce29df)

Was there a reason that this was not included in the main push?

**Comment by korymath** [comment]
Passing all the tests now, even the elusive missing API key test which I re-included.

**Comment by korymath** [comment]
Changed the .travis.yml to test on my own https://travis-ci.org/korymath/gym-http-api

Wondering how the testing development is coming along?

**Comment by catherio** [comment]
Hi @korymath, deepest apologies for my negligence in responding to requests on this repository. I just saw your blog post - very exciting! I'll merge your pull request now. Going forward, are you interested in being given permissions to maintain this repository so that you can make Lua improvements more easily?

(On the testing front, as you perhaps can tell, I got halfway through adding CI to this repo, but did not get it all the way set up, so these failures are essentially meaningless.)

**Comment by korymath** [comment]
Hi @catherio, no worries at all. I imagined it was supportive work, and that there was a backlog on your end. 
I would be interested in helping out on the direct repository, thank you for the offer. Is there anything critically outstanding I can jump on right now?
Happy to help on Travis if I can as well.

**Pull request merged**
